version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    working_directory: ~/project/Backend
    steps:
      - checkout
      - run:
          name: Clear npm cache
          command: npm cache clean --force
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
