version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            curl -sSL "https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v18.0.0-linux-x64/bin/node
            curl -sSL https://www.npmjs.com/install.sh | sudo bash
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
