jobs:
  build:
    docker:
      - image: cimg/node:18
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            cd frontend  # Navigate to the directory containing package.json
            npm install   # Install dependencies
            npm run build # Build the project
      - sonarcloud/scan
